config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :students
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  get '/about', to: 'static_pages#about'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/student.rb
class Student < ApplicationRecord
  after_commit :add_default_img, on: %i[create update]
  belongs_to :user
  scope :search_by_name, ->(name) { where("CONCAT_WS(' ', first_name, last_name) ILIKE ?", "%#{name}%") }
  scope :search_by_name_and_course, lambda { |name, course|
                                      where("(CONCAT_WS(' ', first_name, last_name)) ILIKE ? AND course ILIKE ?",
                                            "%#{name}%", "%#{course}%") }
  scope :search_by_name_and_year, lambda { |name, year|
                                      where("(CONCAT_WS(' ', first_name, last_name)) ILIKE ? AND year_level ILIKE ?",
                                            "%#{name}%", "%#{year}%") }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :middle_name, presence: true
  validates :address, presence: true
  validates :civil_status, presence: true
  validates :gender, presence: true
  validates :course, presence: true
  validates :year_level, presence: true
  validates :mother_name, presence: true
  validates :father_name, presence: true
  validates :parent_address, presence: true
  validates :birthday, presence: true
  validates :birth_place, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :phone_number, presence: true
  validates :att_elem, presence: true
  validates :att_hs, presence: true
  has_one_attached :image

  def self.courses
    ['Bachelor of Science in Information Technology',
     'Bachelor of Science in Business Administration',
     'Bachelor of Science in Criminology']
  end

  def self.year_levels
    %w[I II III IV]
  end

  def self.search_options
    [['Name', ['name']],
     ['Course', ['Bachelor of Science in Information Technology',
                 'Bachelor of Science in Business Administration',
                 'Bachelor of Science in Criminology']],
     ['Year Level', %w[I II III IV]]]
  end

  def add_default_img
    unless image.attached?
      image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default.jpeg')),
                        filename: 'default.jpg', content_type: 'image/jpg')
    end
  end

  def display_image
    image.variant(resize_to_limit: [80, 80])
  end

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true
class StudentsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :create, :update, :destroy]
  before_action :correct_user, only: :destroy
  # GET /students or /students.json
  def index
    @students = Student.order(params[:sort]).paginate(page: params[:page])
    @students = Student.search_by_name(params[:keyword]).paginate(page: params[:page]) if params[:filter] == 'name'
    if Student.courses.include?(params[:filter])
      @students = Student.search_by_name_and_course(params[:keyword], params[:filter]).paginate(page: params[:page])
    elsif Student.year_levels.include?(params[:filter])
      @students = Student.search_by_name_and_year(params[:keyword], params[:filter]).paginate(page: params[:page])
    end
  end

  # GET /students/1 or /students/1.json
  def show
    set_student
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    set_student
  end

  # POST /students or /students.json
  def create
    @student = current_user.students.build(student_params)

    if @student.save
      flash[:success] = "Student #{"#{@student.first_name} #{@student.last_name}"} was successfully added!"
      redirect_to @student
    else
      render 'edit'
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    set_student

    if !@student.user_id.nil?
      @student.user_id = current_user.id
    end
    
    if @student.update(student_params)
      flash[:success] = "Student #{"#{@student.first_name} #{@student.last_name}"} was successfully updated."
      redirect_to student_url
    else
      render 'edit'
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    set_student
    if !@student.nil?
      flash[:success] = "Student #{"#{@student.first_name} #{@student.last_name}"} was successfully deleted."
      @student.destroy
    else
      flash[:danger] = 'There was a problem deleting student.'
    end
    redirect_to root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:first_name, :middle_name, :last_name, :course, :year_level,
                                    :email, :phone_number, :address, :mother_name, :father_name,
                                    :spouse, :att_elem, :att_hs, :att_coll, :religion, :parent_address,
                                    :fb_account, :birthday, :birth_place, :gender, :civil_status, :image,
                                    :filter, :keyword)
  end

  def correct_user
    @student = current_user.students.find_by(id: params[:id])
    redirect_to(root_url) unless admin? || !@student.nil?
  end
end

app/helpers/students_helper.rb
module StudentsHelper
  
end

app/views/students/_form.html.erb
<div class="card">
  <h5 class="card-title text-lg-center mt-lg-4">Basic Information</h5>
  <div class="card">
    <div class="row">
      <div class="col-md-12 mb-4">
        <div class="form-outline mb-3">
          <%= f.label "Upload picture:", class: "form-label" %>
          <span class="card-img form">
          <%= f.file_field :image, class: "form-control form-control-sm", accept: "image/jpeg,image/gif,image/png" %>
          </span>
        </div>
    </div>
    <div class="row">
      <div class="col-md-4 mb-4">
        <div class="form-outline">
          <%= f.label :first_name, class: "form-label" %>
          <%= f.text_field :first_name, class: "form-control form-control-sm" %>
        </div>
      </div>

      <div class="col-md-4 mb-4">
        <div class="form-outline">
          <%= f.label :middle_name, class: "form-label" %>
          <%= f.text_field :middle_name, class: "form-control form-control-sm" %>
        </div>
      </div>

      <div class="col-md-4 mb-4">
        <div class="form-outline">
          <%= f.label :last_name, class: "form-label" %>
          <%= f.text_field :last_name, class: "form-control form-control-sm" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 mb-4 pb-2">
        <%= f.label :address, class: "form-label" %>
        <%= f.text_field :address, class: "form-control form-control-sm" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 mb-4 d-flex align-items-center">
        <div class="form-outline date w-100" id="datepicker">
          <%= f.label "Birthday (YYYY-MM-DD)", class: "form-label" %>
          <%= f.text_field :birthday, class: "form-control form-control-sm", id: "date" %>
          <i class="fas fa-calendar input-prefix"></i>
        </div>
      </div>

      <div class="col-md-6 mb-4">
        <div class="form-outline">
          <%= f.label :birth_place, "Birthplace", class: "form-label" %>
          <%= f.text_field :birth_place, class: "form-control form-control-sm" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 mb-4 d-flex align-items-center">
        <div class="col-md-6 mb-4">
          <h6 class="mb-2 pb-1">Gender: </h6>
          <div class="form-check form-check-inline">
            <%=f.label :gender, "Male", value: "Male", class: "form-check-label" %>
            <%=f.radio_button :gender, "Male", class: "form-check-input" %>
          </div>
          <div class="form-check form-check-inline">
            <%=f.label :gender, "Female", value: "Female", class: "form-check=label" %>
            <%=f.radio_button :gender, "Female", class: "form-check-input" %>
          </div>
        </div>
      </div>
      <div class="col-md-6 mb-4 d-flex align-items-center">
        <div class="col-md-6 mb-4">
          <h6 class="mb-2 pb-1">Civil Status: </h6>
          <div class="form-check form-check-inline">
            <%=f.label :civil_status, "Single", value: "Single", class: "form-check=label" %>
            <%=f.radio_button :civil_status, "Single", class: "form-check-input" %>
          </div>
          <div class="form-check form-check-inline">
            <%=f.label :civil_status, "Married", value: "Married", class: "form-check=label" %>
            <%=f.radio_button :civil_status, "Married", class: "form-check-input" %>
          </div>
          <div class="form-check form-check-inline">
            <%=f.label :civil_status, "Widow", value: "Widow", class: "form-check=label" %>
            <%=f.radio_button :civil_status, "Widow", class: "form-check-input" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="card">
  <h5 class="card-title text-lg-center mt-lg-4">Contact Information</h5>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4 mb-2 pb-2">
        <div class="form-outline">
          <%= f.label :email, class: "form-label" %>
          <%= f.email_field :email, class: "form-control form-control-sm" %>
        </div>

      </div>
      <div class="col-md-4 mb-2 pb-2">
        <div class="form-outline">
          <%= f.label :phone_number, class: "form-label" %>
          <%= f.phone_field :phone_number, class: "form-control form-control-sm" %>
        </div>
      </div>
      <div class="col-md-4 mb-2 pb-2">
        <div class="form-outline">
          <%= f.label :fb_account, class: "form-label" %>
          <%= f.phone_field :fb_account, class: "form-control form-control-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="card">
  <h5 class="card-title text-lg-center mt-lg-4">Course Information</h5>
  <div class="card-body">
    <div class="row">
      <div class="col-md-9 mb-4 pb-2">
        <%= f.label :course, class: "form-label" %>
        <%= f.select :course, Student.courses %>
      </div>
      <div class="col-md-3 mb-4 pb-2">
        <%= f.label :year_level, class: "form-label" %>
        <%= f.select :year_level, Student.year_levels %>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="card">
  <h5 class="card-title text-lg-center mt-lg-4">Family Information</h5>
  <div class="card-body">
    <div class="row">
      <div class="col-md-6 mb-4 pb-2">
        <%= f.label :father_name, "Father's Name", class: "form-label" %>
        <%= f.text_field :father_name, class: "form-control form-control-sm" %>
      </div>
      <div class="col-md-6 mb-4 pb-2">
        <%= f.label :mother_name, "Mother's Name", class: "form-label" %>
        <%= f.text_field :mother_name, class: "form-control form-control-sm" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 mb-4 pb-2">
        <%= f.label :parent_address, "Parent's Address", class: "form-label" %>
        <%= f.text_field :parent_address, class: "form-control form-control-sm" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 mb-4 pb-2">
        <%= f.label :spouse, class: "form-label" %>
        <%= f.text_field :spouse, class: "form-control form-control-sm" %>
      </div>
    </div>
  </div>
</div>
<hr>
<div class="card">
  <h5 class="card-title text-lg-center mt-lg-4">School History</h5>
  <div class="card-body">
    <div class="row">
      <div class="col-md-12 mb-4 pb-2">
        <%= f.label :att_elem, "Elementary", class: "form-label" %>
        <%= f.text_field :att_elem, class: "form-control form-control-sm" %>
      </div>
      <div class="col-md-12 mb-4 pb-2">
        <%= f.label :att_hs, "High School", class: "form-label" %>
        <%= f.text_field :att_hs, class: "form-control form-control-sm" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 mb-4 pb-2">
        <%= f.label :att_coll, "College", class: "form-label" %>
        <%= f.text_field :att_coll, class: "form-control form-control-sm" %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/students/_student.html.erb
<tr class="candidates-list">
  <td>
    <div class="candidate-list-details">
      <div class="candidate-list-info">
        <div class="candidate-list-title">
          <h5 class="mb-0"><%= link_to student.full_name, student_path(student) %></h5>
        </div>
      </div>
    </div>
  </td>
  <td>
    <div class="candidate-list-option d-inline text-lg-center">
        <span><%= student.course  %></span>
    </div>
  </td>
  <td class="candidate-list-favourite-time text-lg-center">
    <span class="candidate-list-time order-1"><%= student.year_level %></span>
  </td>
  <td>
    <ul class="mb-0 d-flex justify-content-lg-center align-content-center list-unstyled">
      <li>
        <%= link_to student_path(student), class: "btn btn-sm btn-info m-1" do %>
          <i class="bi bi-binoculars-fill"></i>
        <% end %>
      </li>
      <% if current_user?(student.user) || admin? %>
        <li>
          <%= link_to edit_student_path(student), class: "btn btn-sm btn-primary m-1" do %>
            <i class="bi bi-pencil-fill"></i>
          <% end %>
        </li>
        <li>
          <%= link_to student_path(student), method: :delete, data: {confirm: 'Are you sure you want to delete this student?'}, 
          class: "btn btn-sm btn-danger m-1" do %>
            <i class="bi bi-trash-fill"></i>
          <% end %>
        </li>
        <% end %>
    </ul>
  </td>
</tr>

app/views/students/edit.html.erb
<%= provide(:title, "Edit Student") %>
<%= provide(:button_text, "Save Changes") %>
<section class="min-vh-100 gradient-custom">
  <div class="container py-5 min-vh-100">
    <div class="row justify-content-center align-items-center">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Student Profile - Edit Form</h3>
            <div class="form-group">
              <%= form_with(model: @student, local: true) do |f| %>
                <%= render'shared/error_messages', object: f.object %>
                <%= render 'form', f: f %>
                <div class="text-lg-center">
                  <%= f.submit yield(:button_text), class: "btn btn-primary btn-lg" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/students/index.html.erb
<%= provide(:title, 'Students List') %>
<p id="notice"><%= notice %></p>
<div class="d-flex justify-content-center min-vh-100">
  <div class="col-lg-9 mt-4 mt-lg-0">
    <div class="row p-4 m-auto">
      <div class="col-2 d-flex justify-content-center align-text-center">
        <h5>Search Students</h5>
      </div>
      <div class="col-8 justify-content-center align-text-center">
        <%= render 'shared/student_search_form' %>
      </div>
      <div class="col-2 justify-content-lg-end">
        <%= link_to new_student_path, class: "btn btn-primary mb-3" do %>
            <i class="bi bi-person-plus-fill"></i>Add Student
        <% end %>
      </div>
    </div>
    <div class="row card">
        <div class="col-md-12">
        <div class="user-dashboard-info-box table-responsive mb-0 bg-white p-4 shadow-sm">
          <table class="table manage-candidates-top mb-0 table-striped table-hover caption-top">
            <caption>Search/Student List Results</caption>
            <thead>
            <tr>
              <th class="text-lg-center"><%= link_to "Student Name", :sort => "first_name" %></th>
              <th class="text-lg-center"><%= link_to "Course", :sort => "course" %></th>
              <th class="text-lg-center-center"><%= link_to "Year Level", :sort => "year_level" %></th>
              <th class="action text-lg-center">Action</th>
            </tr>
            </thead>
            <tbody>
              <%= render @students %>
            </tbody>
          </table>
          <div class="pagination justify-content-center">
            <%= will_paginate %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<%= provide(:title, "Add Student") %>
<%= provide(:button_text, "Add Student") %>

<section class="min-vh-100 gradient-custom">
  <div class="container py-5 min-vh-100">
    <div class="row justify-content-center align-items-center">
      <div class="col-12 col-lg-9 col-xl-7">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-4 p-md-5">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Student Profile - Registration Form</h3>
            <%= form_with(model: @student, local: true) do |f| %>
              <%= render 'shared/error_messages', object: f.object %>
              <%= render 'form', f: f %>
              <div class="text-lg-center">
                <%= f.button yield(:button_text), class: "btn btn-primary btn-lg" do %>
                  <i class="bi bi-person-fill-add"></i><%= yield(:button_text) %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/students/show.html.erb
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <%= image_tag @student.image , class: "rounded-circle img-fluid" if @student.image.attached? %>
            <h5 class="my-3"><%= @student.full_name %></h5>
            <p class="text-muted mb-1"><%= @student.course + " " + @student.year_level %></p>
            <p class="text-muted mb-4"><%= @student.address %></p>
            <div class="d-flex justify-content-center mb-2">
              <% if current_user?(@student.user) || admin? %>
                <%= link_to edit_student_path(@student), class: "btn btn-outline-success ms-1" do %>
                  <i class="bi bi-pencil-fill"></i> edit
                <% end %>
                <%= link_to @student, method: :delete, data: { confirm: "Are you sure you want to delete this student record?" },
                class: "btn btn-outline-danger ms-1" do %>
                  <i class="bi bi-trash-fill"></i> delete
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.full_name %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.email %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Contact Number</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.phone_number %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Gender</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.gender %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Civil Status</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.civil_status %></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.address %></p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Date of Birth</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.birthday %></p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Place of Birth</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.birth_place %></p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Religion</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= @student.religion %></p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4"><span class="text-primary font-italic me-1"></span> Schools Attended
                </p>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Elementary:</p>
                <div class="row">
                  <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @student.att_elem %></p>
                  </div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">High School:</p>
                <div class="row">
                  <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @student.att_hs %></p>
                  </div>
                </div>
                <p class="mt-4 mb-1" style="font-size: .77rem;">College:</p>
                <div class="row">
                  <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @student.att_coll %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4"><span class="text-primary font-italic me-1"></span> Family</p>
                <p class="mb-1" style="font-size: .77rem;">Father's Name</p>
                <div class="row">
                  <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @student.father_name %></p>
                  </div>
                </div>
                <p class="mb-1" style="font-size: .77rem;">Mother's Name</p>
                <div class="row">
                  <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @student.mother_name %></p>
                  </div>
                </div>
                <p class="mb-1" style="font-size: .77rem;">Spouse's Name</p>
                <div class="row">
                  <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @student.spouse %></p>
                  </div>
                </div>
                <p class="mb-1" style="font-size: .77rem;">Parent's Address</p>
                <div class="row">
                  <div class="col-sm-9">
                    <p class="text-muted mb-0"><%= @student.parent_address %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>