config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :students
  root 'sessions#new'
  get '/login', to: 'sessions#new'
  get '/about', to: 'static_pages#about'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="nav navbar-nav d-flex justify-content-center align-items-center sticky-bottom bg-dark text-white">
  <div class="col-md-4 d-flex align-items-center">
    <%= link_to '#', class: 'mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1' do %>
      <%= image_tag image_path('pcc_logo.png'), class: 'd-flex align-text-middle' %>
      Philippine Countryville College, Inc.
    <% end %>
  <div class="nav col-md-4 justify-content-end d-flex">
      © 2023 Copyright
  </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <%= link_to '#', class:'navbar-brand' do %>
        <%= image_tag image_path('pcc_logo.png'), class: 'd-inline-block align-text-middle' %>
        Philippine Countryville College, Inc. - Student Profiling System
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
          <% if logged_in? %>
            <% if admin? %>
              <li class="nav-item" >
                <%= link_to "Manage Users", users_path, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item" >
              <%= link_to "Manage Students", students_path, class: "nav-link" %>
            </li>
            <li class="dropdown nav-item d-flex">
              <%= image_tag current_user.display_thumb_image , class: "rounded-circle img-fluid" if current_user.image.attached? %>
              <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown" role="button">
                 <%= current_user.first_name %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
                <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                <li><hr class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item" >
              <%= link_to "About", about_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= favicon_link_tag asset_path('pcc_logo.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %> alert-dismissable fade show", role: "alert">
        <%= message %>
        <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      <% end %>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <div class="container-fluid">
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>